name: train_random_forest
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas=2.1.3
  - scikit-learn=1.4.0
  - pip=23.3.1
  - pip:
      - wandb==0.16.0
      - mlflow==2.8.1
